# Site settings
title: Alevin-Tutorial
description: 'A support website for Alevin-tool (part of Salmon). How Tos and FAQs'
url: 'https://combine-lab.github.io'
baseurl: '/alevin-tutorial'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Combine-lab (Stony Brook University)'
  email: asrivastava@cs.stonybrook.edu
  twitter_username: k3yavi
  #  facebook_username: joshgerdes
  github_username:  COMBINE-lab
  #  linkedin_username:  joshgerdes

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
